name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  microvmi:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: install latest libmicrovmi package
        run: |
          curl -s https://api.github.com/repos/Wenzel/libmicrovmi/releases/latest | jq -r '.assets[].browser_download_url' | wget -qi - -O microvmi.deb
          sudo dpkg -i microvmi.deb
          rm microvmi.deb

      - name: compile microvmi LeechCore device plugin
        run: make -C leechcore_device_microvmi
